### PR TITLE
Adding warning for ctors

### LINKED ISSUE #42: default ctor for Node and Tool
It seems that Godot requires default ctor and would brake if it is not there.
Would be nice, if Rider produce a warning or an error in such case.

### PR DESCRIPTION
**Pull request by Nepp3r**
Adding highlighting (warning) if script doesn't contain ctor with 0 arguments and quick fix for it. Also fixing Godot tracker and removing -PskipDotnet=true from arguments for running IDE. Adding internal mode in build.gradle.kts, resolves #42

### CODE REVIEW

**Comment by Nepp3r** [comment]
I haven't yet commited quickfix, because it isn't ready, but the highlighting part is ready and can be inspected for problems. Also I removed 1 argument from the run command, because I think it could be commited accidently because it doesn't belong there

**Comment by van800** [comment]
It looks like it will affect all classes, not only derived from the Godot.GodotObject.
I have some new infrastructure for that in https://github.com/JetBrains/godot-support/pull/126, which will get merged shortly.

**Comment by Nepp3r** [comment]
I've inspected the #126, but I'm not really sure I understand the way it is done. If I have a right direction, I must inspect all IClassDeclaration node types from PSI tree and then, using constants that was added in this PR, check if they are derived from this particular class Godot.GodotObject, am I right?

**Comment by van800** [comment]
image
Once you rebase your work on current net241, you'd be able to add in your analyser Run.

            var typeElement = element.DeclaredElement;
            if (typeElement == null)
                return;

            if (!typeElement.DerivesFromGodotObject()) // could you please check if it only makes sense for the Node or all GodotObjects?
                return;
            
It would ensure that other classes unrelated to Godot would not be affected by the new analyzer.

**Comment by Nepp3r** [comment]
Added and tested mechanism for quickfix and added validation for classes, so the issue must be resolved now

**Comment by van800** [comment]
Some wording improvement could be done.
I think using term "parameterless constructor" would be better then "Constructor with no parameters" and "empty constructor with no parameters"

**Comment by van800** [comment]
Try to use similar wording as Godot documentation:
here is what I have found https://docs.godotengine.org/en/latest/tutorials/scripting/resources.html#creating-your-own-resources
(in the C# example)
        // Make sure you provide a parameterless constructor.
        // In C#, a parameterless constructor is different from a
        // constructor with all default values.
        // Without a parameterless constructor, Godot will have problems
        // creating and editing your resource via the inspector.

**Comment by Nepp3r** [comment]
Would be ConstructorElementProblemAnalyzer, NoParameterlessConstructorError and ParameterlessConstructorQuickFix appropriate naming for classes?

**Comment by Nepp3r** [comment]
Also _Add parameterless constructor_ and _Parameterless constructor is required to initialize a script/game object_ as messages for users

**Comment by Nepp3r** [comment]
Yeah, sure

**Comment by van800** [comment]
Additionally we can use external annotations to mark the default ctor as UsedImplicitly.

**Pull request merged**
