### PR TITLE
Provide completions for "res://" paths

### PR DESCRIPTION
**Pull request by gipsond**
Addresses #39.

Provides one-level path completions like [idea-file-path-autocomplete](https://github.com/PinkFloyded/idea-file-path-autocomplete), the plugin referenced in the issue. These completions are only provided for string literals starting with `res://`.

As an additional feature, provides full path completions to files with appropriate file extensions. 
Appropriate file extensions are inferred based on `Load`'s type argument or the assignment destination's type, if available.
For example,
```
var scene = GD.Load<PackedScene>("res://...");
                                        ^cursor here
```
will suggest full paths to all `.tscn` files in the Godot project, for example `Scenes/Player.tscn`.

These completions also work on partially completed paths starting with `res://`.

## Testing
I manually tested the completions in Rider as prepared by the `runIde` Gradle task.
To the best of my memory, I tested the following scenarios in a Godot project. The project contained resource files of each type I tested, none of which were at the top level of the Godot project. Full file paths were provided as expected. `...` indicates the position of the cursor.
- `GD.Load<PackedScene>("res://...")`
- `GD.Load<PackedScene>("res://Scenes/...")`
- `GD.Load<PackedScene>("res://Scenes/../...")`
- `GD.Load<PackedScene>("res://../...")` (-> no suggestions provided, path leads outside project directory)
- `ResourceLoader.Load<PackedScene>("res://...")`
- `GD.Load<AudioStream>("res://...")`
- `GD.Load<AudioStreamMP3>("res://...")`
- `GD.Load<AudioStreamSample>("res://...")`
- `GD.Load<Script>("res://...")`
- `GD.Load<CSharpScript>("res://...")`

## Notes
This is my first time contributing to an open-source project, and my first time developing a Resharper or IntelliJ Platform plugin. I didn't attempt to match the existing code style, so please let me know if you would like any adjustments.

I didn't do any automated testing because I couldn't find any automated testing set up in the project and I don't know how to set that up myself.

### CODE REVIEW

**Comment by van800** [comment]
Great to see a contribution.
You can use this https://github.com/JetBrains/godot-support/blob/baf8c271647379a819efd010029d93819adfc329/resharper/src/ProjectModel/ProjectExtensions.cs#L10
to check if the project is really a Godot one.
I suppose this completion provider should be avoided for non-Godot projects.

**Comment by gipsond** [comment]
Ok, adding that now. But I've loaded 3 different Godot projects of mine and `IsGodotProject` returns `false` for each of them. All of their project configurations contain the `GODOT;` constant definition, but they seem to be represented as `UnsupportedProjectConfiguration`s, not `CSharpProjectConfiguration`s. What does R#/Rider need for the project configurations to be recognized as C#?

**Comment by van800** [comment]
I am not an expert in Completion, but here are my thoughts.
1. res:// path completion can be useful also outside cs files.
2. we need to exclude folders and files, which are not in the project. I mean like `.idea` folder. There must be a better approach than using file-system directly. I will ask around.
3. maybe the `ItemsProviderOfSpecificContext<CompletionContextInStringLiterals>` can be used as a base for this.

**Comment by van800** [comment]
Regarding the `IsGodotProject` check and logging potential exceptions, I would write it like the following:
```
        protected override bool AddLookupItems(CSharpCodeCompletionContext context, IItemsCollector collector)
        {
            if (!IsAvailable(context))
                return false;

            var project = context.NodeInFile.GetProject();
            if (project == null)
                return false;

            if (!project.IsGodotProject())
                return false;

            return Logger.CatchSilent(() =>
            {
                var projectPath = context.ProjectPath();
                if (projectPath is null)
                    return false;
                var stringLiteral = context.StringLiteral();
                if (stringLiteral is null)
                    return false;

                var prefix = "res://";
                if (!(stringLiteral.ConstantValue.AsString() is string originalString
                      && originalString.StartsWith(prefix)))
                {
                    return false;
                }

                var relativePathString = originalString.Substring(prefix.Length);
                var searchPath = VirtualFileSystemPath.ParseRelativelyTo(relativePathString, projectPath);

                // If path leads outside project (e.g., due to `..` going up too many levels), don't provide completions.
                if (!searchPath.IsDescendantOf(projectPath))
                {
                    return false;
                }

                var completions =
                    FullPathCompletions(context, searchPath)
                        .Concat(OneLevelPathCompletions(searchPath));

                var items =
                    (from completion in completions.Distinct()
                        select new ResourcePathItem(originalString, completion, context.CompletionRanges))
                    .ToList();
                foreach (var item in items)
                {
                    collector.Add(item);
                }

                return !items.IsEmpty();
            });
        }
```

**Comment by gipsond** [comment]
Thanks for the examples! I was having trouble finding how to log in the R# code. I'll add in the checks you suggest at the top of `AddLookupItems`, as well as checks for the same conditions as intellij-gdscript. Ignoring dotfiles, Godot import files, and `project.godot` makes sense to me.

I recently took a look at the related issue #4 and noticed that [evelant mentioned Godot provides a service for code completion](https://github.com/JetBrains/godot-support/issues/4#issuecomment-664639217). The service provides resource path and node path completion suggestions. Guessing by [the source](https://github.com/godotengine/godot/blob/f5978f4d97150d9e7a1598f9637f0f3c06d72d33/modules/mono/editor/code_completion.cpp#L141), the suggestions for resource paths include full paths to all files in the project, and the suggestions for scene paths are the same, but limited to `.tscn` and `.scn` files. 

What do you think about using this service for completions? This PR provides more specific filtering than the service for other types of `Resource`s, so for now I still want to continue this PR **without using the service**. Later, to address #4 and avoid duplication, it may be nicer to switch to using the service and add the improved `Resource` filtering to Godot itself. [Godot is also finalizing the features for 4.0](https://godotengine.org/article/godot-4-0-development-enters-feature-freeze) so I'd rather wait until 4.0 releases to set up a client for the Godot service or to contribute there, after all the major changes are made to the codebase.

**Comment by van800** [comment]
I still hope for the @citizenmatt review.

**Review by citizenmatt — APPROVED** [review]
Hi all. Apologies for the delay. I've left a few comments.

This is a great initial implementation, but I think it would be worth looking into a different approach at some point in the future. The current method will provide completion of file paths, but Rider supports "path references", which allow a string literal to be bound to an actual path. This gives a lot more features, such as completion, but also ctrl+click navigation, find usages on a file to show where it's used in the code, and it can also handle rename. (I also have some concerns about hitting the disk for each completion, as Rider will eagerly calculate completion items as the caret is moved, and I suspect the path references have some caching.)

However, this is a somewhat more involved process, and I can't point to an example of this being used. Rider has several path reference providers, but they're all fairly bespoke - "injecting" a path into a string literal via a comment, or using it in asp.net MVC apps, etc. Understanding how to add it in this scenario would require some research. 

So I think this approach is a great starting place. Thanks for the contribution @gipsond!

**Comment by van800** [comment]
I have fixed the icons
image

**Comment by van800** [comment]
One bug, which I'd like to approach before merging is the case, when path after res:// is partially typed:
image
Completing it causes adding path to already typed part.
image

**Comment by van800** [comment]
Ok, fixed that. Ready to merge.

**Pull request merged**
