### PR TITLE
Run NUnit tests in Godot process

### PR DESCRIPTION
**Pull request by van800**
Addresses https://github.com/godotengine/godot-proposals/issues/432

**Requires changes in Rider backend. Otherwise conflicts with Unity plugin.**

To use this plugin with Rider 2020.3 EAP you would need to:
1. Disable Unity plugin in Rider Settings->Plugins->Installed
image
2. Download custom plugin from https://github.com/JetBrains/godot-support/suites/1493788264/artifacts/26005321
3. Extract `artifact.zip` somewhere - you would have `rider-godot-2020.3.9999.zip`
4. Install plugin from disk - point it to `rider-godot-2020.3.9999.zip`
image
5. Put `test_runner` folder with files from here https://github.com/van800/godot-demo-projects/tree/nunit/mono/dodge_the_creeps/test_runner to your own project.

You may study the whole example in https://github.com/van800/godot-demo-projects/pull/5 to see, what different types of tests can be done.

### CODE REVIEW

**Comment by herocrab** [comment]
Does this plugin only work with Rider 2020.3 EAP, or will 2020.2.4 also work?

Will this test plugin interfere or inhibit the main Godot/Rider (2020.3.38) plug-in?

**Comment by van800** [comment]
@herocrab 
1. only 2020.3 EAP
2. custom plugin is build on top of latest sources in net203 branch. it si expected to have everything, which was in the build, which you have mentioned.

**Comment by herocrab** [comment]
I initially tried to use this on my own game and noticed dotCover is not reporting anything. I then tried your repo and I'm not able to launch any unit tests. I click any of the green "run" buttons for a test and nothing happens. This is on 2020.3 EAP with the custom plugin.

**Comment by herocrab** [comment]
Looks like I received a couple of exceptions, here is an example of one:

com.jetbrains.rdclient.util.BackendException: Component descriptor JetBrains.ReSharper.UnitTestFramework.UnitTestHost [Singleton, Corrupted] is corrupted and cannot be accessed

--- EXCEPTION #1/2 [InvalidOperationException]
Message = “Component descriptor JetBrains.ReSharper.UnitTestFramework.UnitTestHost [Singleton, Corrupted] is corrupted and cannot be accessed”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
HResult = COR_E_INVALIDOPERATION=80131509
Source = JetBrains.Platform.ComponentModel
StackTraceString = “
  at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.ComponentContainerEx.GetComponent[TInterface](IComponentContainer container)
     at JetBrains.ReSharper.Host.Features.UnitTesting.Actions.RiderUnitTestRunTreeAction.GetHostProviderDescriptor()
     at JetBrains.ReSharper.UnitTestFramework.Actions.UnitTestRunTreeActionBase.BuildContextTree(IDataContext context)
     at JetBrains.ReSharper.UnitTestFramework.Actions.UnitTestRunTreeActionBase.Update(IDataContext context, ActionPresentation presentation, DelegateUpdate nextUpdate)
     at JetBrains.Application.UI.ActionsRevised.Handlers.ExecutableActionEvaluator.Evaluate(IAction handler, EvaluatedAction result, IDataContext context)
     at JetBrains.ReSharper.Feature.Services.Actions.ServicesActionEvaluator.Evaluate(IAction handler, EvaluatedAction result, IDataContext context)
     at JetBrains.Application.UI.ActionsRevised.Handlers.BoundAction.Evaluate(IDataContext context)
     at JetBrains.Platform.RdFramework.Actions.Backend.RdActions.CreateEvaluatedActionDescriptor(IActionDefWithId actionDefWithId, IDataContext dataContext, IActionHandlers handlers)
     at JetBrains.Platform.RdFramework.Actions.Backend.RdActionsAsyncAvailability.UpdateAction(ActionUpdateRequestData req, IDataContext dataContext)
     at JetBrains.Platform.RdFramework.Actions.Backend.RdActionsAsyncAvailability.UpdateOnBackgroundThread(IPriorityQueue`1 actionsToUpdate)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Component descriptor JetBrains.ReSharper.UnitTestFramework.UnitTestHost [Singleton, Corrupted] is corrupted and cannot be accessed”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception exception, ExceptionOrigin origin, String comment)
     at JetBrains.Platform.RdFramework.Actions.Backend.RdActionsAsyncAvailability.UpdateOnBackgroundThread(IPriorityQueue`1 actionsToUpdate)
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
     at System.Threading.Tasks.Task.Execute()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask()
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc()
     at JetBrains.Util.Reflection.CallStackAnnotation.InvokeAnnotated(String classNameOfNewFrame, String methodNameOfNewFrame, Action actionToAnnotate)
     at JetBrains.Util.Reflection.CallStackAnnotation.CatchAnnotatedInvocation[TClassOfNewFrame](String methodNameOfNewFrame, Action actionToAnnotate)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
”

	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:49)
	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:24)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:39)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:30)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.a(RdDispatcher.kt:96)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by herocrab** [comment]
My apologies and failure, I assumed the Unity plugin was not installed/included by default. I saw that it was and disabled it and it is now working. I will give it a test on my game.

**Comment by herocrab** [comment]
Not able to get it working in my own game. I get the following:

image

I put the test_runner directory in my base game. The tests are in a separate project similar to your example. All I'm trying to do is this:

image

Any help is greatly appreciated, I can't stand writing stuff without tests. :)

**Comment by van800** [comment]
@herocrab 
Please contact me on discord `van800#9412`, if you like.
Make sure, you have [this](https://github.com/van800/godot-demo-projects/pull/5/files#diff-ce74f4683232a2b37179fb2e83ddc41063bb56641bd4905aac1c6b5b70ad972cR1) 
in your unit test project.

**Comment by herocrab** [comment]
I was able to get this working in my game. I had been using a .csproj for .NET Unit Testing (the template from Rider) and noticed your projected used the more simplified Godot .csproj. I changed mine to this and cleaned up the references and it is now working in my game. 

@van800 Can you add any brief explanation as to how this is working? I'm assuming you are calling the game with a path to the runner.tscn through the plugin?

**Comment by van800** [comment]
How this works:
1. In the plugin, we override standard behavior, so instead of directly starting Rider-unit-test-runner, we start Godot with `runner.tscn` in [commandline](https://github.com/JetBrains/godot-support/pull/58/files#diff-814839d334a9aca50a5d0200140fa88707a536a1315a80ee8a757fded0621bccR41-R42)
Path to Rider-unit-test-runner is passed to that Godot. 
2.1. `runner.tscn` loads script `EntryPoint.cs`
2.2. `EntryPoint.cs` reads its commandline and takes args, which point to Rider-unit-test-runner and its args. 
2.3. Those args are used to [load](https://github.com/van800/godot-demo-projects/pull/5/files#diff-aa46dfb07482a0bcd08b344a4935b32cc2e8ac339b7d1e32825f878176863916R32) Rider-commandline-unit-test-runner inside Godot process.
2.4. Rider-unit-test-runner establishes its own communication with main Rider, runs tests and passes results.
@herocrab

**Comment by Flavelius** [comment]
It would be nice if this didn't require disabling the unity plugin (i use godot for hobby projects, but unity for work)

**Comment by van800** [comment]
I understand that for sure.

**Comment by van800** [comment]
Planned to be published with Rider 2020.1 EAP1. Compatibility with Unity was resolved.

**Comment by Flavelius** [comment]
The extra files would probably be a good candidate for a godot addon. This way they would be contained in a 'standard location', and the addon would even have the ability to open a socket or create some other additional form of communication channel with rider for other project file related tasks.

**Comment by alfredbaudisch** [comment]
Has anyone managed to make NUnit/XUnit tests work for Godot 4?

**Comment by geowarin** [comment]
Yes, Nunit tests work for me.
See : https://github.com/geowarin/GodotUnitTests

If you are using the latest EAP you can keep use this project as-is (with the test and game csproj cleanly separated from the sln), otherwise, use this commit: https://github.com/geowarin/GodotUnitTests/commit/a4d2ac2bceeae8403599d226a92823b84d3e4cde

**Comment by van800** [comment]
Pure xunit works only to some extent, check the https://github.com/van800/godot-demo-projects/tree/net6/mono/dodge_the_creeps . But there is a wip on godotxunit port to Godot 4 https://github.com/fledware/GodotXUnit/pull/20.

**Comment by theashtronaut** [comment]
I've not been able to get tests to work on Godot 4. I've switched to the NetCoreRunner files featured in
https://github.com/geowarin/GodotUnitTests
and also tried the one from 
 https://github.com/van800/godot-demo-projects/tree/net6/mono/dodge_the_creeps
 
 The tests are not run and say inconclusive. The window pops up like before (in 3.x) but immediately closes.
 
 I even tried the most basic test:
 ```    
    [Test]
    public void Test1()
    {
        GD.Print("Test Hello");
        var main = ResourceLoader.Load<PackedScene>("res://empty.tscn").Instantiate<Main>();
        Assert.AreEqual(new StringName("Node3D"), main.Name);
    }
 ```
 
Using Godot Engine v4.1.stable.mono.official.970459615
JetBrains Rider 2023.2, Build #RD-232.8660.212, built on July 31, 2023
NUnit 3.13.3
Tried both dotnet 6.0 and dotnet 7.0, no differences.

The session file doesn't seem to throw and obvious to me errors.

[2023-08-04-10-48-24-993___e770c8d2-def6-489d-8221-34afcbb5e532.log](https://github.com/JetBrains/godot-support/files/12263327/2023-08-04-10-48-24-993___e770c8d2-def6-489d-8221-34afcbb5e532.log)

Any idea on why it isn't working out for me? I'm sure I've done something wrong!

**Comment by jakeboxer** [comment]
@van800 thanks for your hard work on this, I've been using it to great success and we've got over 400 tests running in just a few seconds in Rider!

Unfortunately, I haven't figured out a way to run the tests from the command line, which means I can't get any CI up and running on GitHub or GitLab or anything. Do you know if this is possible currently? And if not, could you point me in the right direction for adding support for this to Godot myself?

Note: I'm `jakecard` on Discord if you want to talk it through there!

**Pull request merged**
